name: Linting

on:
  pull_request:
    types: [main, opened, reopened, synchronize, edited]
  push:
    branches: [ "main" ]


jobs:
  code-linting:
    name: Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64

      - run: |
          pip install bandit black codespell pylint ruff mypy==1.2.0
          pip install types-requests
      - run: bandit -x ./tests -r pyvet || true
      - run: black --diff --check .
      - run: codespell --skip=./tests,.git,*.css,*.csv,*.html,*.ini,*.ipynb,*.js,*.json,*.lock,*.scss,*.txt,*.yaml
      - run: mypy --ignore-missing-imports --no-implicit-optional --no-warn-no-return pyvet
      - run: pylint --rcfile=.pylintrc --ignore-paths=tests/ -rn pyvet
      - run: ruff pyvet

  markdown-link-check:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out the code
      - name: Lint Code Base
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: "./*.md ./pyvet/**/*.md ./docs/**/*.md"
